version: '3'
services:
  django:
    build: .
    volumes:
      - ".:/code"
    links:
      - selenium
    ports:
      - "8000:8000"
    environment:
      - FLAG=1l0v3c5s
  selenium:
    build: selenium
    ports:
      - 4444:4444
      - 5900:5900